### ISSUE TITLE
paint_pomological strange results

### ISSUE THREAD

**Issue by stas-malavin** [gadenbuie/ggpomological#5]
Hello,
I'm trying to reproduce the density_plot example from README.
In RStudio, an incorrect picture is shown:
![ggpomo](https://user-images.githubusercontent.com/17991942/51177112-cc83d700-18cf-11e9-960f-6b7bd31c70ff.png)
In the pure R, no plot is produced.
In both cases a tibble is printed:
```
# A tibble: 1 x 7
  format width height colorspace matte filesize density
  <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
1 PNG      800    500 sRGB       TRUE         0 38x38 
```
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
R version 3.5.1 (2018-07-02)
RStudio 1.1.442
Mozilla/5.0 (X11; N; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) RStudio Safari/538.1 Qt/5.4.2

**Comment by gadenbuie** [comment]
Hi @stas-malavin and thanks for the report. The `theme_pomological_fancy()` function uses the `magick` package, which in turn relies on your installation of `libmagick++`. Can you please report which version of libmagick you are using by running

```
magick::magick_config()$version
```

I was able to reproduce this issue with version `6.9.7.4`. I was also able to resolve the issue by upgrading ImageMagick to `6.9.10.24`, or the latest version of ImageMagick6.

I built ImageMagick from source by running

```bash
cd Downloads
wget http://imagemagick.org/download/ImageMagick-6.9.10-24.tar.gz
tar -xvf ImageMagick-6.9.10-24.tar.gz
cd ImageMagick-6.9.10-24
./configure
make
sudo make install
sudo ldconfig /usr/local/lib
```

After this, you'll need to re-install `magick` in R so that it is linked to the updated version of `libmagick++`.

```bash
Rscript -e "install.packages('magick')"
```

And then verify that you have the correct version installed with `magick::magick_config()$version`.

Please let me know if the above steps work for you.

**Comment by stas-malavin** [comment]
Thank you @gadenbuie , that was a version issue (indeed, ImageMagick-6.9.7.4 from the Debian repo, but also magic-1.5.9).
So, what I did is building the last version of ImageMagick from source as you suggested, upgrading R (3.5.1 -> 3.5.2), and then reinstalling ggpomological (thus upgrading magic automatically).
Now it works just fine.

**Comment by gadenbuie** [comment]
Glad to hear that worked!
